services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt:ro
      - ./acme-webroot:/var/www/certbot:ro
    networks:
      - TyrsbjergNet

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
     - ./acme-webroot:/var/www/certbot:rw
     - ./certs:/etc/letsencrypt
    command: renew --webroot -w /var/www/certbot --quiet
    #Keep it out of `docker compose up` by default
    profiles: ["manual"]

  redis:
    image: redis:alpine
    networks:
      - TyrsbjergRedis


networks:
  TyrsbjergNet:
    name: TyrsbjergNet 
    driver: bridge    
  TyrsbjergRedis:
    name: TyrsbjergRedis 
    driver: bridge    
